app:
  name: "@artifactId@"
  version: "@revision@"

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:file:./data/h2